#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
target=$(realpath $DIR/http/)

$DIR/run-rigid

docker run \
    --name samfunnsomlafting_web \
    -v $target:/usr/share/nginx/html:ro \
    -e VIRTUAL_HOST=samfunnsomlafting.no \
    -d nginx
